#!/bin/sh
#
# Copyright (c) Siemens AG, 2026
#
# Authors:
#  Tobias Schaffner <tobias.schaffner87@outlook.com>
#
# SPDX-License-Identifier: MIT

set -ex

# Set login banner (overwrite base-files /etc/issue at postinst time)
hostname=$(cat /etc/hostname 2>/dev/null || echo "ros-xenomai")
echo "${hostname} (login: root/root)" > /etc/issue

# isc-dhcp-server
systemctl enable dhclient.service

# ntpsec is started with high priority in newer debian versions
# this can lead to high latencies on unisolated cores.
if [ -w "/etc/default/ntpsec" ]; then
   sed -i 's|NTPD_OPTS="-g -N"|NTPD_OPTS="-g"|g' /etc/default/ntpsec
   sed -i 's|IGNORE_DHCP=""|IGNORE_DHCP="yes"|g' /etc/default/ntpsec
fi
